### PR TITLE
Feature/pipenv and notebooks

### LINKED ISSUE #2: Feature : Notebooks chapter 1
## TODO
- [x] Add  euler/crank-nicolson (type figure 1.7) Colab Notebook
- [x] Add interactive graph for each méthod with Fo as a slider slider

### PR DESCRIPTION
**Pull request by YannSc**
Work in Progress
- [x] Adding Pipenv file
- [x] Edit Readme Pipenv file
- [x] Creating notebook with interactive plots (ongoing) for the Chapter 1

Other examples will be modified the same way

### CODE REVIEW

**Comment by YannSc** [comment]
For the Crank Nicholson scheme, the books uses the method
```python
def fc_CN(Tp,T,K,beta,Fo):
return Tp -T - beta*Fo*np.dot(K,T) - beta*Fo*np.dot(K,Tp)
```
whereas in the code, `Fo` is not an argument of the method. Which parameters should be used for the interactive graph ? 

https://github.com/eddes/buildingphysics/blob/b39822b695ffccd3c22ad04c3295951d770e6483/chapter_1/3_crank_nicolson_layer_air_interface.py#L6-L7

**Comment by YannSc** [comment]
Les notebooks ont été portés sous Colab. Il reste pour PCM et IAQ à modifier les paramètres pour les plots interactifs.

**Comment by eddes** [comment]
> 
> 
> Les notebooks ont été portés sous Colab. Il reste pour PCM et IAQ à modifier les paramètres pour les plots interactifs.

Super ! Je vais tenter de faire des modifs depuis pycharm, je te tiens au jus.

**Comment by eddes** [comment]
> 
> 
> For the Crank Nicholson scheme, the books uses the method
> 
> ```python
> def fc_CN(Tp,T,K,beta,Fo):
> return Tp -T - beta*Fo*np.dot(K,T) - beta*Fo*np.dot(K,Tp)
> ```
> 
> whereas in the code, `Fo` is not an argument of the method. Which parameters should be used for the interactive graph ?
> 
> https://github.com/eddes/buildingphysics/blob/b39822b695ffccd3c22ad04c3295951d770e6483/chapter_1/3_crank_nicolson_layer_air_interface.py#L6-L7

Good one: I guess the time step \Delta t is the parameter to be chosen. 
As Fourier is a function of Fo=a*dt/dx^2 putting dt in the slider is probably a sounder pedagogical option.

**Comment by YannSc** [comment]
> > For the Crank Nicholson scheme, the books uses the method
> > ```python
> > def fc_CN(Tp,T,K,beta,Fo):
> > return Tp -T - beta*Fo*np.dot(K,T) - beta*Fo*np.dot(K,Tp)
> > ```
> > 
> > 
> > whereas in the code, `Fo` is not an argument of the method. Which parameters should be used for the interactive graph ?
> > https://github.com/eddes/buildingphysics/blob/b39822b695ffccd3c22ad04c3295951d770e6483/chapter_1/3_crank_nicolson_layer_air_interface.py#L6-L7
> 
> Good one: I guess the time step \Delta t is the parameter to be chosen.
> As Fourier is a function of Fo=a*dt/dx^2 putting dt in the slider is probably a sounder pedagogical option.

Slider with dt has been added in buildingphysics/chapter_1/3_crank_nicolson_layer_air_interface.py

**Comment by YannSc** [comment]
Notebook chapter one contains the three schemes approach. Good for review / completion and merge.

**Pull request merged**
